### ISSUE TITLE
[Feature] - FC Support

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#13]
It's nice to keep track of which arrangements you've FC (Full Combo) - got 100% on in Score Attack.  Unfortunately, Rocksmith doesn't keep track of this in the save file; you have to track it outside the game.

Here's kind of what I'm thinking...

- Add fields to the `songs_owned` database for tracking this..
  - Either `sa_easy_fc`/`sa_medium_fc`/`sa_hard_fc`/`sa_master_fc` as booleans
  - Or `sa_easy_fc_at` / `sa_medium_fc_at` / `sa_hard_fc_at` / `sa_master_fc_at` as dates, to store when FC was achieved 
- On the view that pops up when you click an arrangement, add input for getting FC Status next to the "Delete Song from DB" and other buttons
- On the SongList view, where it shows the little badges for SA, add a little glowy halo or something around the platinum pick if it's FC'd
- On the Dashboard "Score Attack" stats view, add a tier above "Plat" for "FC"

What are your thoughts about adding FC-tracking in general, and the approach?

**Comment by sandiz** [comment]
what kind of input do you prefer ? checkbox input ?

**Comment by JustinAiken** [comment]
> what kind of input do you prefer ? checkbox input ?

Would personally prefer date input, so I can keep track of when I first got it; but checkbox would also be okay - any tracking is better than none 😄

**Comment by sandiz** [comment]
fixed in v0.8.0

FC's can be entered via Song Details  (Date Input)
![image](https://user-images.githubusercontent.com/5438703/45915607-854b7500-be0c-11e8-9fb6-606310bffb1e.png)

since i am tracking stats across all sa difficulties, i am showing all of them in dashboard now
![image](https://user-images.githubusercontent.com/5438703/45915615-a2804380-be0c-11e8-9ea6-b5504db2b2ef.png)

specific sa stat pane can be toggled via Settings
![image](https://user-images.githubusercontent.com/5438703/45915618-bc218b00-be0c-11e8-9e0e-b14b9a9542d1.png)

**Comment by sandiz** [comment]
Let me know what you think, feel free to open new issues for feedback/bugs
