### ISSUE TITLE
Unplayable arrangements in songs.psarc

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#4]
If you scan in the `songs.psarc` to get all the on-disc progress, it grabs some unplayable arrangements, called like `RS2 Test Disc Riffs - Hybrid Tails`

![screen shot 2018-07-27 at 7 55 10 pm](https://user-images.githubusercontent.com/1568662/43351916-233cc94c-91d7-11e8-8944-8aafa7290863.png)

**Comment by sandiz** [comment]
hi @JustinAiken, thanks for the feedback

fixed in [alpha5.1](https://github.com/sandiz/rs-manager/releases/tag/alpha5.1)

psarcExplorer will no longer import test tracks (song names starting with`RS2 Test` or `RS2 Chord`)
also added a `Delete Song` button in song detail view, so you can delete those entries manually instead of reimporting everything again
![image](https://user-images.githubusercontent.com/5438703/43359395-b1509ebe-9256-11e8-9220-330af2de8f47.png)

**Comment by JustinAiken** [comment]
Perfect, thanks!
