### ISSUE TITLE
Create setlists for ODLC packs

### ISSUE THREAD

**Issue by JustinAiken** [sandiz/rs-manager#55]
## Data
Here's a [csv](https://gist.github.com/JustinAiken/0cba27a4161a2ed3ad54fb6a58da2e70) that has the DLC pack / date / arrangement_id for all current songs

## Import

- It would be cool to have a button in settings that would autocreate setlists matching
  - Even better if it would only create the setlists for the packs you actually have
- I hacked it in to my own local sqlite database directly with [this hacky ruby script](https://gist.github.com/JustinAiken/a335853cbc1998027f0b41636b0e8e5c)
  - But that's not helpful to anyone else...

## End Result:

![Screen Shot 2019-03-27 at 4 58 10 PM](https://user-images.githubusercontent.com/1568662/55117797-9aea7180-50b1-11e9-8f45-41227d6d4ecf.png)

**Comment by BuongiornoTexas** [comment]
Hi Justin,

Could I clarify - what is the difference between a set list and a song list? I know that the latter is the six song lists provided in the Rocksmith UI - I'm curious if a set list is something else, or another name for song list?

Cheers,

Larry

**Comment by JustinAiken** [comment]
> Could I clarify - what is the difference between a set list and a song list? I know that the latter is the six song lists provided in the Rocksmith UI - I'm curious if a set list is something else, or another name for song list?

- Rocksmith itself has the six songlists, plus favorites
  - This are limited, and apply to all arrangements in the song
- RS Manager can import those
- But it also has it's own setlists; these are very flexible
  - For manual setlists, you can add individual arrangements
  - For generated setlists, you can apply filters (tuning, difficulty, playcount, etc)
  - But Rocksmith itself doesn't know they exist - they're just for reference

**Comment by BuongiornoTexas** [comment]
> But Rocksmith itself doesn't know they exist - they're just for reference

Ah! I'd misinterpreted what rs-manager does - Along with the stat reporting and set list creation, I thought it allowed exporting of setlists into the Rocksmith profile as Songlists.

My question was also a bit leading - I put together some python code last year that a) can generate song lists in a similar fashion to rs-manager (although much uglier - currently configured through json filter definitions rather than a rs-manager style UI) and b) can write these song lists back to a steam profile and also tidies up all of the Rocksmith metadata and steam metadata along the way (basically handles a safe write to steam profile process). 

I've been using this code quite happily for the last 9 months (I use song lists extensively to manage my practice sessions), and I'm in the process of cleaning it up and converting to a package for wider release (rsrtools). The functionality for writing song lists to profile is pretty solid as is.*

If rs-manager could be set up to export one or more song/set lists to a text file, it would be pretty easy to add functionality to my code to read the song list file and then load the lists into a Rocksmith profile. 

If you or Sandi are interested in this functionality, I'm happy to spend time working on it. Let me know!

Cheers,

Larry

* Caveat: Solid for Windows only. Sorting OSX requires updates to a small number of routines for finding steam user information and folders - I'd need help from someone with an OSX machine for this.

**Comment by sandiz** [comment]
@JustinAiken thanks for curating the csv, i'm working on the import as well as adding a search function to setlists

@BuongiornoTexas rsrtools sounds like a great tool. i can definitely
 - add code to export setlist as a txt or csv
 - as well as, add an integration option with rsrtools directly, if its ok with you . 
(an example of integration: i am currently using @kokolihapihvi Rocksniffer in rs-manager to power some parts of [rocksmith live](https://raw.githubusercontent.com/sandiz/rs-manager/master/screenshots/images/rslive-phrases.png) feature via local http)

justin and I are both macos users, can definitely help port! 😇

**Comment by BuongiornoTexas** [comment]
@sandiz Great on both the export and integration options! I'll stop polluting this issue and raise a feature request.

I'll get back to you and @JustinAiken later on the macos help - I have a very old mac, so I'll see if I can get Steam/Rocksmith up and running on that first.

**Comment by JustinAiken** [comment]
> Ah! I'd misinterpreted what rs-manager does - Along with the stat reporting and set list creation, I thought it allowed exporting of setlists into the Rocksmith profile as Songlists.

As of now, it's read only, no writing...

> I put together some python code last year that [....] can write these song lists back to a steam profile and also tidies up all of the Rocksmith metadata and steam metadata along the way (basically handles a safe write to steam profile process).

I've been working on that in my similar [ruby-based tool](https://github.com/JustinAiken/rsgt), but haven't been able to get binary-perfect writing (if no changes)... yet.  I don't want to write to my savefile until I know that it's absolutely safe :)  But would be great to be able to delete progress for old customs I've deleted from my library and not going to play again... 🤔 

>  I'm in the process of cleaning it up and converting to a package for wider release (rsrtools). 

Sweet! Can never have enough tools 😀 

> Sorting OSX requires updates to a small number of routines for finding steam user information and folders - I'd need help from someone with an OSX machine for this.

If you can follow Ruby (it's pretty clear), [here's](https://github.com/JustinAiken/rsgt/blob/d374b7797239b18d36a4c3cd8c7326ddd5ca003e/lib/rsgt/steam.rb) how to get the file location, extract the profiles id from that, then load that file (I'm guessing you already have the decryption figured out 😉) on OSX.  I'm not sure if the [key](https://github.com/JustinAiken/rsgt/blob/master/lib/rsgt/encrypted_steam_file.rb#L11-L16) is different on Win then osx... 

> i'm working on the import as well as adding a search function to setlists

😂

**Comment by BuongiornoTexas** [comment]
@JustinAiken Maybe a tiny bit more pollution then. 

> but haven't been able to get binary-perfect writing (if no changes)

This issue was pretty well the core focus of my [save file module](https://github.com/BuongiornoTexas/rsrtools/blob/master/rsrtools/files/savefile.py). When you create a save file instance, the constructor will load and unpack the save and then try to recreate a byte perfect reconstruction of the save - the constructor will fail if this doesn't work. There is a minor caveat on these checks - I can't reconstruct the padding Ubi uses pre-compression (see comments in code for my ugly workaround). As I've been running for months without trouble, I'm assuming that Rocksmith discards this pad when it loads the savefile. 

I figure this fail without reconstruct approach allows identification of changes in the file format by Ubisoft or corruption in the source file. 

On top of this, before writing new data to the save files, the profile manager makes a zipfile backup of the **entire** Rocksmith user data directory. (I'm really paranoid about my saves!)

> I don't want to write to my savefile until I know that it's absolutely safe.

Same! The way I got around this was to create a separate testing profile which I wasn't worried about corrupting.

> But would be great to be able to delete progress for old customs.

This may be as simple as pruning out all json elements for those arrrangement ids? I'll put it in as a feature request for the profile manager. It already implements a play count editor, song list replacement, and profile cloning (very useful for testing).

>  here's how to get the file location

Thanks - that'll be a good starting point. I think the only place encryption differs between platforms is in some of the files in the psarcs.

**Comment by sandiz** [comment]
fixed in https://github.com/sandiz/rs-manager/releases/tag/2.0.0

adds import, search setlist by name and export setlist (exported as json array containing song keys) to file functionality.

**Comment by JustinAiken** [comment]
Uh-oh, looks the link coded in the app won't pick up updates I make...
- `https://gist.github.com/JustinAiken/0cba27a4161a2ed3ad54fb6a58da2e70` is the canonical gist URL
- `https://gist.githubusercontent.com/JustinAiken/0cba27a4161a2ed3ad54fb6a58da2e70/raw/53959dbcfbf715d19a7140c34f815d648fcf9528/dlcs.csv` is the raw URL hardcoded in the app
- `https://gist.githubusercontent.com/JustinAiken/0cba27a4161a2ed3ad54fb6a58da2e70/raw/93dd9821e6c3c363096ff897e27370e290ce9a5a/dlcs.csv` is the raw URL after I updated the csv gist w/ new Radiohead songs
- I *think* that just `https://gist.githubusercontent.com/JustinAiken/0cba27a4161a2ed3ad54fb6a58da2e70/raw` would work to always get the latest...
