### ISSUE TITLE
[Feature Request] Integrate with rsrtools

### ISSUE THREAD

**Issue by sandiz** [sandiz/rs-manager#58]
implement integration with `importrsm` 

https://github.com/BuongiornoTexas/rsrtools/issues/6

**Comment by BuongiornoTexas** [comment]
Hi Sandi,

One thing did occur to - me it's probably worth putting a warning up about not modifying saves while RS is running (it might or might not work - I'll do some experimenting in the future). 

Cheers,

Larry

**Comment by sandiz** [comment]
will do!

**Comment by sandiz** [comment]
fixed in [v2.1.1](https://github.com/sandiz/rs-manager/releases/tag/v2.1.1)

thanks for `importrsm` @BuongiornoTexas, worked perfectly on mac and windows! 😇💯

**Comment by BuongiornoTexas** [comment]
Awesome work on the implementation and turn around! 

And I've got to admit you are somewhat braver than I - I spend an awful lot of time working with Test profiles before I leap to modifying my main line save.

I may have picked up a bug - I'm trying out the export/import feature and it looks as though things are hanging on "Processing, please wait ...". I suspect this is because I run python in a virtual environment - I'll do a bit more digging and try to figure out a solution.

And another minor thing - if you want to offer people the option of bypassing the Steam authorisation, you can get most of the account information from the ``config/loginusers.vdf`` file in the steam installation directory (it's what I use for importrsm checks) - this may be useful for people who don't like using the steam OAuth login. 

And again, nice work! (and have a great weekend)

Cheers,

Larry

**Comment by BuongiornoTexas** [comment]
Hi Sandi, 

I think I do have a bug of some form. At this stage, I'm getting the 'Processing, please wait ...' message pretty well everything I do. It may not be related, but I also don't seem to be able to export set lists generated by filters to JSON (manual setlists and setlists loaded from Rocksmith are fine). 

This is on Windows - I'll check out Mac OS tomorrow or Sunday. Stuff I've tried:

- importrsm from a site installation and from a virtual environment. 
- Rocksmith Manager from the portable installation and from the Windows installer.
- Two Rocksmith profiles.
- Starting Rocksmith Manager from a command shell with admin privileges.

I can't see where rs-manager puts the temporary files/folder - if you can point me at them, I can check to see if I can figure out where the problem is happening (as a very long shot, I may even be able to attach a python debugger to see what is going on from the rsrtools side - a lot of learning curve on this!). 

I'm happy to take suggestions on things to try (my exposure to js is limited).

Cheers,

Larry

**Comment by sandiz** [comment]
hi @BuongiornoTexas 

> At this stage, I'm getting the 'Processing, please wait ...

that means the exit event was not fired by the child process, which is odd. does `importrsm` run normally when you run it from cmd line ?

> I can't see where rs-manager puts the temporary files/folder - if you can point me at them,

thanks for doing the investigation, i create a temp folder in %TEMP% whenever export is called. i think you might be able to locate it there (sort by creation date should sort it to top)

>this may be useful for people who don't like using the steam OAuth login.

ya i thought that too, small feature request: is it possible to just pass the path to prfldb instead of steam/profile name pair.. if not i can do the `config/loginusers.vdf` query

> I also don't seem to be able to export set lists generated by filters to JSON (manual setlists and setlists loaded from Rocksmith are fine).

investigating this as well the mystery child process shenanigans..

**Comment by sandiz** [comment]
> I also don't seem to be able to export set lists generated by filters to JSON (manual setlists and setlists loaded from Rocksmith are fine).

pushed a fix for this, it was missing an import 

>  At this stage, I'm getting the 'Processing, please wait ...' 
importrsm seems to be working fine on mac for me, i'll do more investigation on windows. can you check the console log and see if any error was reported ? (console log is accessible via edit->toggle developer tools)

**Comment by JustinAiken** [comment]
Just gave this a try for the first time... The modal recognizes my profile name, but when I hit the export get this error:

![Screen Shot 2019-05-03 at 1 29 15 PM](https://user-images.githubusercontent.com/1568662/57160935-761ba500-6da7-11e9-94c8-e060e97b6206.png)

Here's that error in text form: 

```python
Traceback (most recent call last):
  File "/usr/local/bin/importrsm", line 6, in <module>
    from rsrtools.importrsm import main
  File "/usr/local/lib/python3.7/site-packages/rsrtools/importrsm.py", line 21, in <module>
    from rsrtools.songlists.database import ArrangementDB
  File "/usr/local/lib/python3.7/site-packages/rsrtools/songlists/database.py", line 40, in <module>
    from rsrtools.files.profilemanager import RSProfileManager, JSON_path_type
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/profilemanager.py", line 1016, in <module>
    class RSProfileManager:
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/profilemanager.py", line 1100, in RSProfileManager
    _steam_accounts: SteamAccounts = SteamAccounts()
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/steam.py", line 191, in __init__
    self._account_info = self._find_info()
  File "/usr/local/lib/python3.7/site-packages/rsrtools/files/steam.py", line 263, in _find_info
    name = login_info["AccountName"]
KeyError: 'AccountName'
```

**Comment by sandiz** [comment]
@BuongiornoTexas 
i just released a recovery [build](https://github.com/sandiz/rs-manager/releases/tag/v2.1.2) which fixes #59, i added a couple of extra logs when executing `importrsm` and now handling both exit and error events (instead of just 'close').. 
if there is any error when invoking `importrsm` it should print in the console. can you please share the logs when you get a chance ?

![image](https://user-images.githubusercontent.com/5438703/57160140-c7726700-6d9c-11e9-839a-9595d1f71f9b.png)

thanks for helping me with the investigation!

**Comment by sandiz** [comment]
@JustinAiken thanks for the stack trace, from the code... it looks like it found the steam login info but the vdf file is missing some info ?

will you be able to share your ~/Library/Application\ Support/Steam/config/loginusers.vdf file ?

@BuongiornoTexas let me know if i am looking at the right place

**Comment by JustinAiken** [comment]
```
"users"
{
	<# removed in case it's sensitive> 
	{
		"accountname"		"justinaiken"
		"PersonaName"		"JustinAiken"
		"RememberPassword"		"1"
		"Timestamp"		"1556751550"
		"WantsOfflineMode"		"0"
		"SkipOfflineModeWarning"		"0"
		"mostrecent"		"1"
	}
}
```

**Comment by JustinAiken** [comment]
Oh hmm...

> KeyError: '`AccountName`'
> `accountname`

wonder if it's a sensitivity thing?

**Comment by sandiz** [comment]
oh could be, mine is in CamelCase

```
"users"
{ 
        "#"
        {
                "AccountName"           "#"
                "PersonaName"           "0zymandias"
                "RememberPassword"              "1"
                "mostrecent"            "1"
                "Timestamp"             "1556868899"
                "WantsOfflineMode"              "0"
        }
}
```

i've opened a bug with https://github.com/BuongiornoTexas/rsrtools/issues/12

**Comment by JustinAiken** [comment]
Anyways, manually edited my .vdf file to have that key in camelcase.
- Did a dump of my current save's uncompressed .json
- Exported a few songs from rs-manager into rsrtools song list 3
- Did a dump of that save:
```
--- current.json	2019-05-03 14:55:05.000000000 -0600
+++ exported.json	2019-05-03 14:56:14.000000000 -0600
@@ -7778,10 +7778,13 @@
 "MindEraser",
 "VolbHeav"
 ],

 [
+"GretEdge",
+"GretWnth",
+"GretYour"
 ],

 [
 "RancRuby",
 "RancTime",
```

Looks like it nails it!

**Comment by BuongiornoTexas** [comment]
Justin, glad that's got it working, and sorry for my delay in responding. The joys of living half a world away (beautiful sunrise though!).

On to my contributions:

- The Steam Accounts vdf bug is indeed case sensitivity (Steam - wonderful some days, pile of inconsistencies the next). I'll push a fix as soon as I can make time. 

>  is it possible to just pass the path to prfldb instead of steam/profile name pair.

- Yes. I'll push this at the same time. 

I still think there is a case for implementing a loginusers.vdf solution, as it will work better for users that aren't familiar with Steam folder structures. I'll put together a low priorty feature enhancement request in the next few days.

- My problem isn't a virtual environment issue, and importrsm runs OK from the command line. 

I'm downloading the recovery fix now - I'll let you know what I find.

**Comment by sandiz** [comment]
>I still think there is a case for implementing a loginusers.vdf solution, as it will work better for users that aren't familiar with Steam folder structures. 

yup totally agree, i meant it as an optional parameter, that way we can use either of the options depending on what info we have in hand

> sorry for my delay in responding. The joys of living half a world away (beautiful sunrise though!).

no problem at all! absolutely no rush, feel free to respond whenever appropriate. Have a great rest of the day! ☀️

**Comment by BuongiornoTexas** [comment]
I've just run the recovery release, and while I now get an error message, it doesn't look all that helpful.

![image](https://user-images.githubusercontent.com/48264358/57166879-e590a380-6e3e-11e9-91c6-b2f4a7384480.png)

From a quick check, it looks as though this is a missing file error.

I've checked the Temp folder - the songkeys.json file is created, so this is good. I'd guess this means the sub-process can't find importrsm? 

I'd check the console log, but I need a bit more guidance on how to get to it. At the moment, I'm starting rs-manager from "Rocksmith Manager.exe", and I can't see anything obvious on accessing a developer mode. I'm guessing that I need to be running from an ide for this? 

The other thing I can do is a quick hack to importrsm to log to file so that we can check if a) it starts and b) where it gets to.

**Comment by sandiz** [comment]
it will be in the top level menu, if its not shown press alt to make it appear

something similar to this
![image](https://user-images.githubusercontent.com/5438703/57167709-90f41680-6db3-11e9-9236-f1d439459374.png)

from the error it looks like it didnt find the importrsm binary maybe
can you see if there is any path listed in Settings->RS Songlist->Path to importrsm
![image](https://user-images.githubusercontent.com/5438703/57167773-cf89d100-6db3-11e9-8f47-5815f653ab68.png)

**Comment by BuongiornoTexas** [comment]
Got it! It's a space-in-path problem - I setup a new version of rsrtools without a space in the path and was able to run properly, I'm guessing the syscall doesn't protect the path to importrsm against this?

I'll see if I can provide more from the developer console - thanks for the help on finding it!

**Comment by sandiz** [comment]
ohhhh great catch, i can definitely escape the space before invoking

**Comment by BuongiornoTexas** [comment]
No more detail in the console log unfortunately. 

I'll get onto to the rsrtool updates shortly - should be out by Monday (maybe quicker, but it's looking like a busy weekend).

**Comment by sandiz** [comment]
fixed in [v2.1.3](https://github.com/sandiz/rs-manager/releases/tag/v2.1.3). paths are now quoted on windows. let me know if it doesnt work!

**Comment by BuongiornoTexas** [comment]
Working beautifully now. 

Cheers,

Larry

**Comment by BuongiornoTexas** [comment]
Hi Sandi, 

importrsm has a --prfldb-path option in [0.2.1](https://github.com/BuongiornoTexas/rsrtools/releases/tag/0.2.1beta).

Cheers,

Larry
